### ISSUE TITLE
1.x-2.x browser OTP and Cubic Ninja OTP FBI

### ISSUE THREAD

**Issue by arromdee** [Plailect/Guide#243]
If you start with a typical firmware, following the guide will put FBI on your EmuNAND, then later restore it to a9lh SysNAND.

Following the guide if you have 1.x-2.x skips step 4, so there is no EmuNAND and no FBI inject

The browser OTP and Cubic Ninja OTP parts should have something telling people to inject FBI.  Technically, they already have a9lh even without it, but in practice, having it is pretty much essential.

**Comment by dark-samus** [comment]
...wut?

**Comment by arromdee** [comment]
dark-samus: There is a special section of the guide which you are supposed to follow if your 3DS's firmware is 1.x or 2.x.  People who still have those old firmwares crop up surprisingly often.

If you follow the instructions in the guide for those firmwares, you will not have FBI, because you skipped part 4, and that part installs FBI by injection.

FBI is, in practice, so essential to using CFW that there should be a step at the end to install FBI, since it was not installed in step 4.

**Comment by arromdee** [comment]
Also, unrelated issue (mentioned on IRC): Section 2 says "If you are already on 9.2.0-20, skip to step 22."  This should read "If you are already on 9.2.0-20, copy Emunand9 (step 3), then skip to step 22."

**Comment by Plailect** [comment]
>The browser OTP and Cubic Ninja OTP parts should have something telling people to inject FBI.

Fixed

>Note that having non-20 is possible.

Yes, but the point is to get everyone to 9.2.0-20 before the 2.1.0 downgrade

>create an empty otp.bin file first

That shouldn't make a difference...

**Comment by arromdee** [comment]
>Yes, but the point is to get everyone to 9.2.0-20 before the 2.1.0 downgrade

It is possible that someone started with a machine that is 9.2 with some low browser.  It is also possible that someone started with a low firmware and cart-upgraded to 9.2.  In either case, they would be at that point in the guide without a -20 browser, so the guide should not specify having -20 at that point.

Furthermore, you need to include the text "copy Emunand9 (step 3), then".  If they skip to step 22, they won't be able to pass step 23 since they won't have Emunand9.

>That shouldn't make a difference...

[First link where it made a difference](https://www.reddit.com/r/3dshacks/comments/4rei7a/3dshacking_qa_thread_ask_questions_here/d53hm61)

[Second link where it made a difference:](http://gbatemp.net/threads/what-to-buy-2-2-0-or-8-1-0-regarding-installing-a-cfw.421725/page-2#post-6528977)

**Comment by Plailect** [comment]
Added "Section II - Injecting FBI"

The point is that even if they have a low browser, they should perform the "downgrade" to install the correct browser to prevent any issues.

Added empty otp.bin thing, I do actually recall someone mentioning this way back in initial testing of the Cubic Ninja payload

**Comment by arromdee** [comment]
I don't think that telling someone with 9.2 and a low browser to "downgrade" to 9.2 is a good idea.

Also, this still doesn't say "copy Emunand9 (step 3), then", even though that step is necessary.

**Comment by Plailect** [comment]
It's fine to install full 9.2 over a partial 9.2 install...

added the step 3 thing

**Comment by dark-samus** [comment]
@Plailect tell them to just do an update, that's actually safer than doing a downgrade (only the titles that are needed will be installed, and nothing will be uninstalled)

**Comment by arromdee** [comment]
I don't see what issues would be caused by not having the correct browser.  They would use a non-browser entry point to downgrade to 2.1.  That's one less step[ than using a non-browser entry point to get the proper browser and then the browser to downgrade to 2.1.

**Comment by dark-samus** [comment]
Do you know how hard it is to maintain one version of the guide, let alone 2 or 3 versions for all of the different circumstances? If you want your "perfect" guide, go write it yourself

**Comment by arromdee** [comment]
I'm not saying the entire guide is bad, just the one line.  And I'm quite willing to write the one line.
